version: '3.9'

services:
#  localstack:
#    container_name: localstack
#    image: 'localstack/localstack:latest'
#    ports:
#      - "127.0.0.1:4566:4566"            # LocalStack Gateway
#      - "127.0.0.1:4510-4559:4510-4559"  # External services port range
#    environment:
#      - AWS_DEFAULT_REGION=us-east-1
#      - SERVICES=sqs,sns,s3,dynamodb
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./init-scripts:/docker-entrypoint-initaws.d
#    networks:
#      - online-store-network

  backend:
#    depends_on:
#      localstack:
#        condition: service_healthy
    image: 'online-store/online-store:latest'
    container_name: online-store
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    restart: always
    ports:
      - "8081:8081"
    networks:
      - online-store-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  online-store-network:
    name: online-store-network