version: '3.9'

networks:
  online-store-network:
    name: online-store-network

services:
  postgresdb:
    image: 'postgres:13.11-bullseye'
    container_name: online-store-postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    networks:
      - online-store-network
    volumes:
      - 'db:/var/lib/postgresql/data'

  sonarqube:
    image: sonarqube:latest
    container_name: onlinestore-sonarqube
    ports:
      - "9011:9011"
    networks:
      - online-store-network
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  db:
