version: '3.9'
services:

  #
  # Localstack
  #
  localstack:
    image: 'localstack/localstack:latest'
    container_name: localstack
    build:
      context: ./
      dockerfile: docker/localstack/Dockerfile
    hostname: awslocal
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    user: root
    environment:
      DEBUG: 0
      SERVICES: "sqs,sns,dynamodb"
      HOSTNAME_EXTERNAL: awslocal
      PERSISTENCE: "/var/lib/localstack/state"
      AWS_DEFAULT_REGION: us-east-1
      DYNAMODB_SHARE_DB: 1
      DYNAMODB_IN_MEMORY: 1
      EDGE_PORT: 4566
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-scripts:/etc/localstack/init/ready.d"
    networks:
      - online-store-app-network
    profiles:
      - prod
      - test

  #
  # Online Store App
  #
  online-store-app:
    image: 'online-store/online-store:latest'
    container_name: online-store
    build:
      context: ./
      dockerfile: docker/online-store-app/Dockerfile
    ports:
      - '8081:8081'
    user: root
    environment:
      AWS_ENDPOINT_URL: http://awslocal:4566
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
       localstack:
          condition: service_healthy

    deploy:
      replicas: 1
    networks:
      - online-store-app-network
    profiles:
      - prod

networks:
  online-store-app-network:
    driver: bridge