version: '3.9'
services:
  localstack:
    image: 'localstack/localstack:latest'
    container_name: localstack
    hostname: awslocal
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
    user: root
    environment:
      DEBUG: 0
      SERVICES: "sqs,sns"      # Declare which aws services will be used in localstack
      HOSTNAME_EXTERNAL: awslocal
      DATA_DIR: "/var/lib/localstack/data"
      AWS_DEFAULT_REGION: us-east-1  # This is the region where your localstack mocks to be running
      EDGE_PORT: 4566
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-scripts:/etc/localstack/init/ready.d"
  online-store-app:
    image: 'online-store/online-store:latest'
    container_name: online-store
    ports:
      - "8081:8081"
    user: root
    environment:
      AWS_ENDPOINT_URL: http://awslocal:4566
    depends_on:
      localstack:
        condition: service_healthy
    build:
      context: ./
      dockerfile: docker/online-store-app/Dockerfile
    deploy:
      replicas: 1
