version: '3.9'

networks:
  online-store-network:
    name: online-store-network
    external: true

services:
  iced-latte-app:
    image: 'zufarexplainedit/iced-latte-backend:${DOCKER_IMAGE_TAG}'
    container_name: iced-latte-backend
    env_file:
      - .env
    build:
      context: .
      args:
        APP_PROFILE: dev
        APP_VERSION: '${DOCKER_IMAGE_TAG}'
    ports:
      - '${APP_SERVER_PORT}:${APP_SERVER_PORT}'
    networks:
      - online-store-network
