version: '3.9'

networks:
  online-store-network:
    name: '${DOCKER_COMPOSE_NETWORK}'
    external: true

services:
  online-store-app:
    image: '${DOCKER_HUB_ACCOUNT_NAME}/$IMAGE_NAME:${DOCKER_IMAGE_TAG}'
    container_name: dev-backend
    env_file:
      - .env
    build:
      context: .
      args:
        APP_PROFILE: ${APP_PROFILE}
        APP_VERSION: ${APP_VERSION}
    ports:
      - '${APP_SERVER_PORT}:${APP_SERVER_PORT}'
    networks:
      - '${DOCKER_COMPOSE_NETWORK}'
