version: '3.9'

networks:
  online-store-network:
    name: online-store-network

services:
  postgresdb:
    image: 'postgres:13.11-bullseye'
    container_name: online-store-postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    networks:
      - online-store-network
    volumes:
      - /opt/docker/online-store/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
