version: '3.9'

networks:
  online-store-network:
    name: online-store-network
    external: true

services:
  online-store-app:
    image: '${HUB}/online-store:${TAG}'
    container_name: online-store-app
    env_file:
      - .env
    build:
      context: .
    ports:
      - '8083:8083'
    networks:
      - online-store-network
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL}
