
#
# Server Properties
#
server:
  port: ${APP_SERVER_PORT}
  tomcat:
    accept-count: 100

#
# Spring Properties
#
spring:
  application:
    name: Iced Latte Application
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  output:
    ansi:
      enabled: detect

  #
  # Database Properties
  #
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_NAME}?serverTimezone=UTC
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yaml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
#
# Stripe Api Properties
#
  config:
    import: optional:stripe.yaml

#
# Email Properties
#
  mail:
    host: ${SMTP_MAIL_HOST}
    port: ${SMTP_MAIL_PORT}
    username: ${COMPANY_EMAIL_USERNAME}
    password:  ${COMPANY_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust:  ${SMTP_MAIL_HOST:smtp-relay.brevo.com}

iced-latte:
  feature:
    email-confirmation:
      enabled: ${FEATURE_EMAIL_CONFIRMATION_ENABLED:true}
      email-properties:
        from: ${FEATURE_EMAIL_CONFIRMATION_COMPANY_EMAIL}
      base-link: ${FEATURE_EMAIL_CONFIRMATION_BASE_LINK}
      token:
        pattern: '???-???'
        pattern-placeholder-char: '?'

#
# Spring Doc Properties
#
springdoc:
  api-docs:
    path: /api/docs/schema
  swagger-ui:
    path: /api/docs/swagger-ui

#
# Management Properties
#
management:
  server:
    port: ${server.port}
  endpoint:
    prometheus:
      enabled: false
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, shutdown, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

#
# JWT Security Properties
#
jwt:
  header: Authorization
  secret: ${APP_JWT_SECRET}
  expiration: 1800000 # 30 minutes

#
# Login Attempts Properties
#
login-attempts:
  max-attempts: 5
  lockout-duration-minutes: 60

unlock-account-scheduler-cron: '0 0/5 * * * *' # every 5 minutes

#
# Logging Properties
#
logging:
  pattern:
    file: iced-latte-backend-%d{yyyy-MM-dd}.%i.log
  config: classpath:logback-spring.xml
