
#
# Server Properties
#
server:
  port: ${APP_SERVER_PORT}
  tomcat:
    accept-count: 100

#
# Spring Properties
#
spring:
  application:
    name: Online Store Application
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  output:
    ansi:
      enabled: detect
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_NAME}?serverTimezone=UTC
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yaml
    url: jdbc:postgresql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_NAME}?serverTimezone=UTC
    user: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
#
# Stripe Api Properties
#
  config:
    import: optional:stripe.yaml

#
# Spring Doc Properties
#
springdoc:
  api-docs:
    path: /api/docs/schema
  swagger-ui:
    path: /api/docs/swagger-ui

#
# Management Properties
#
management:
  server:
    port: ${APP_SERVER_PORT}
  endpoint:
    prometheus:
      enabled: false
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus
  prometheus:
    metrics:
      export:
        enabled: false
  metrics:
    tags:
      application: ${spring.application.name}

#
# JWT Security Properties
#
jwt:
  header: Authorization
  secret: ${APP_JWT_SECRET}
  expiration: 1800000 # 30 minutes

#
# Login Attempts Properties
#
login-attempts:
  max-attempts: 5
  lockout-duration-minutes: 60

unlock-account-scheduler-cron: '0 0/5 * * * *' # every 5 minutes

#
# Logging Properties
#
logging:
  pattern:
    file: online-store-%d{yyyy-MM-dd}.%i.log
  config: classpath:logback-spring.xml