
# Server Properties
server:
  port: 8081

# Spring Properties
spring:
  application:
    name: aws-services

# AWS Properties
cloud:
  aws:
    service:
      endpoint: http://localhost:4566
    region:
      static: us-east-1
    credentials:
      access-key: aws_access_key_id
      secret-key: aws_secret_access_key
    sqs:
      queue:
        purchase-transactions-sqs-queue-url: http://localhost:4566/000000000000/purchase-transactions-sqs-queue
    sns:
      topic:
        name: purchase-transactions-sns-topic
        url: http://localhost:4566