
# Server Properties
server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: certs/springboot.p12
    key-store-password: password
    key-alias: springboot
    enabled: true

# Spring Properties
spring:
  application:
    name: Online Store Application

# Management Properties
management:
  server:
    port: 8081
  endpoint:
    prometheus:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

# AWS Properties
cloud:
  aws:
    service:
      endpoint: ${AWS_ENDPOINT_URL:http://localhost:4566}
    region:
      static: us-east-1
    credentials:
      access-key: aws_access_key_id
      secret-key: aws_secret_access_key
    sqs:
      queue:
        purchase-transactions-sqs-queue-url: ${cloud.aws.service.endpoint}/000000000000/purchase-transactions-sqs-queue
    sns:
      topic:
        name: purchase-transactions-sns-topic
        url: ${cloud.aws.service.endpoint}

# JWT Security Properties
jwt:
  header: Authorization
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 6044800
