apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: online-store-app
spec:
  selector:
    matchLabels:
      app: online-store-app
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: online-store-app
    spec:
      containers:
        - name: online-store-app
          image: online-store/online-store:latest
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
