openapi: "3.0.3"

info:
  title: "Online-Store API"
  version: "1.0.0"

servers:
  - url: "http://localhost:8083"

tags:
  - name: "Security"
    description: "An API for user registration and authentication"

paths:
  /api/v1/auth/register:
    post:
      tags:
        - "Security"
      summary: "Register a user"
      operationId: "register"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistrationRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserRegistrationResponse"

  /api/v1/auth/authenticate:
    post:
      tags:
        - "Security"
      summary: "Authenticate a user"
      operationId: "authenticate"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAuthenticationRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserAuthenticationResponse"

  /api/v1/auth/confirmation/{token}:
    get:
      tags:
        - "Security"
      summary: "Confirms a user registration email"
      operationId: "confirmEmail"
      parameters:
        - name: "token"
          description: "Unique token for confirming a user registration email"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
        "404":
          description: "Not Found - no user found for the given token or already confirmed"

components:
  schemas:
    UserRegistrationRequest:
      type: "object"
      properties:
        firstName:
          type: "string"
        lastName:
          type: "string"
        email:
          type: "string"
        password:
          type: "string"

    UserRegistrationResponse:
      type: "object"
      properties:
        token:
          type: "string"

    UserAuthenticationRequest:
      type: "object"
      properties:
        email:
          type: "string"
        password:
          type: "string"

    UserAuthenticationResponse:
      type: "object"
      properties:
        token:
          type: "string"