name: Java CI with Maven

on:
  pull_request:
    branches:
      - feature/ci-cd-pipeline-by-zufar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B package -Pdev -DskipTests --file pom.xml

      - name: Upload workspace
        uses: actions/upload-artifact@v2
        with:
          name: workspace
          path: ./

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download workspace
        uses: actions/download-artifact@v2
        with:
          name: workspace
          path: ./

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Run unit tests
        run: mvn test -Pdev --file pom.xml
