name: CI/CD Pipeline for DEV environment

on:
  push:
    branches: [ development ]
  pull_request:
    types: [ closed ]

env:
  PRIVATE_REPO_ACCESS_TOKEN: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
  PRIVATE_REPOSITORY: ${{ secrets.PRIVATE_REPOSITORY }}
  PRIVATE_REPOSITORY_FULL_NAME: Sunagatov/${{ secrets.PRIVATE_REPOSITORY }}
  ENV_FILE_PATH_IN_PRIVATE_REPOSITORY: ${{ secrets.NV_FILE_PATH_IN_PRIVATE_REPOSITORY }}

jobs:
  prepare-env-file:
    runs-on: ubuntu-latest
    steps:
      - name: Copy env from the private repository
        uses: actions/checkout@v4
        with:
          repository: $PRIVATE_REPOSITORY_FULL_NAME
          token: $PRIVATE_REPO_ACCESS_TOKEN
          path: $PRIVATE_REPOSITORY

      - name: Copy .env file
        run: cp $ENV_FILE_PATH_IN_PRIVATE_REPOSITORY ./

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          load-mode: strict

      - name: Upload .env file as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: env-file
          path: .env

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: prepare-env-file
    steps:
      - name: Checkout source code from the repository
        uses: actions/checkout@v4

      - name: Download .env file
        uses: actions/download-artifact@v3
        with:
          name: env-file
          path: .
      - name: Set DOCKER_IMAGE_TAG
        run: echo "DOCKER_IMAGE_TAG=$GITHUB_REF_NAME-${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Build the docker image
        run: |
          export DOCKER_IMAGE_NAME=${{ env.DOCKER_IMAGE_NAME }}
          export DOCKER_IMAGE_TAG=DOCKER_IMAGE_TAG
          export DOCKER_HUB_ACCOUNT_NAME=${{ env.DOCKER_HUB_ACCOUNT_NAME }}
          export DOCKER_COMPOSE_NETWORK=${{ env.DOCKER_COMPOSE_NETWORK }}
          export APP_SERVER_PORT=${{ env.APP_SERVER_PORT }}
          export DOCKER_CONTAINER_NAME=${{ env.DOCKER_CONTAINER_NAME }}
          docker-compose -f $DEV_DOCKER_COMPOSE_FILE build
          export

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$DOCKER_IMAGE_TAG

  deploy-app-to-server:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: Download .env file
        uses: actions/download-artifact@v3
        with:
          name: env-file
          path: .
      - name: Deploy image via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          port: ${{ secrets.DEV_SSH_PORT }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.DEV_SSH_PRIV_KEY }}
          envs: DOCKERHUB_USERNAME, IMAGE_NAME, ENV_BRANCH, DOCKER_IMAGE_TAG
          script: |
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker pull $DOCKER_HUB_ACCOUNT_NAME/$IMAGE_NAME:$DOCKER_IMAGE_TAG
            cd /opt/project/backend-test
            docker-compose -f ${{ env.DEV_DOCKER_COMPOSE_FILE }} up -d
