name: CI/CD Pipeline for DEV environment

on:
  push:
    branches: [ development ]
  pull_request:
    types: [ closed ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  DEV_DOCKER_COMPOSE_FILE: docker-compose.dev.yml
  ENV_BRANCH: ${{ github.ref_name }}

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code from the repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          load-mode: strict

      - name: Set Short SHA
        run: echo "ENV_SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout source code from the repository
        uses: actions/checkout@v4

      - name: Build the docker image
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          docker-compose -f ${{ env.DEV_DOCKER_COMPOSE_FILE }} build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.ENV_BRANCH }}-${{ env.ENV_SHA_SHORT }}

  deploy-to-server:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: Deploy image via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          port: ${{ secrets.DEV_SSH_PORT }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.DEV_SSH_PRIV_KEY }}
          envs: DOCKERHUB_USERNAME, IMAGE_NAME, ENV_BRANCH, ENV_SHA_SHORT
          script: |
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker pull $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ env.ENV_BRANCH }}-${{ env.ENV_SHA_SHORT }}
            cd /opt/project/backend-test
            docker-compose -f ${{ env.DEV_DOCKER_COMPOSE_FILE }} up -d
